### PR TITLE
created a github spergout by changing a few names

### PR DESCRIPTION
**Pull request by robokopter**
naming schemes for events / maps, added a testmap + moved currently unused events there

### CODE REVIEW

**Comment by ltw6610** [comment]
Seems like we both changed things in the same files, I added the slime and changed the events for the monsters. I wouldn't change the map's name, anons might submit maps and we should know the map id to make the overlay. 
But we indeed needed to move the old test events to a another test-map.

**Comment by robokopter** [comment]
Changing map names (or variable/switch names) in RPGMaker is pretty harmless, since it automatically changes all references when you do that. I changed them to make it easier for anyone new to start understanding what the hell is going on.

**Comment by ltw6610** [comment]
If you open the map editor of the Wes' house you'd see that the "Note" has notetags, these notetags points to an overlay that has the map id, deep into the game there might be a lot of mapshots of anons that we have to put into the map so it could become difficult to guess which overlay is for, we could however, change the names but keep the id map on the end.

**Comment by robokopter** [comment]
What do you mean when you say "id" specifically? In the data folder, the maps will always be named Map00xx, and will be numbered in the order they were created in, regardless of the names you assign to them inside the program.

**Comment by ltw6610** [comment]
Map001 has ID 1, so if I want to merge an anon's map into map001 I just have to copy his png file and put it into \img\overlays\grounds folder for exemple and name it "ground1", however if we have dozens of maps that doesn't have their ID visible and on top of that we for exemple decided to arrenge them in the order the story happens then it becomes incredible difficult to guess what id the map has. I could be wrong though correct me if there's another way.

**Comment by robokopter** [comment]
Yeah, so the id works like how I thought. However I don't even know what these overlays are, and why they're needed. Can you tell me which custom plugin is at work here? Cause this method seems completely alien to me.

**Comment by ltw6610** [comment]
There's 2 plugins, "OrangeMapshot" and "OrangeOverlay", the first one serves the purpose of creating a mapshot 1:1 of the map the player is currently in, I create a part of the map and want to share it, I play the game and spawn in-game in the map, then press print screen button and a folder with the mapshot's real resolution pops-up (the editor can't do this if the map is too big the resolution is blurry and shit), then this anon uploads the png file in the thread or forks it here, me or someone else then uses the second plugin "orangeoverlay", place the anon's mapshot into \img\overlays\grounds ground1.png, thus we have the part of the map made by another anon into our already made map.

**Comment by ltw6610** [comment]
Also try to keep future discussions in the thread

**Comment by robokopter** [comment]
Well, I don't want to start any kind of a dispute over this. Clearly both using the plugin AND the naming conventions are our own ways of trying to make contributions more accessible. Simple compromise: rename the maps in RPGM but leave the map ID next to them. Like "World map (1)". Works!
I also like to post with a name, because when I post anonymously, I get horribly irresponsible. But will try.

**Pull request merged**
